site_name: Simulation Summary
theme:
  name: mkdocs
  font:
    text: Itim
nav:
  - Midterm: midterm.md
  # - Home: index.md
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js